"""enforce unique incident assessment

Revision ID: 7bba7c317f58
Revises: a0c180e8e346
Create Date: 2026-09-26 23:20:04.261961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bba7c317f58'
down_revision: Union[str, Sequence[str], None] = 'a0c180e8e346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_incidents', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'security_incidents', ['assessment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'security_incidents', type_='unique')
    op.alter_column('security_incidents', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
