"""add security_incidents table

Revision ID: a0c180e8e346
Revises: d39a57b16627
Create Date: 2026-09-26 15:04:39.078742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c180e8e346'
down_revision: Union[str, Sequence[str], None] = 'd39a57b16627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_incidents_id'), 'security_incidents', ['id'], unique=False)
    op.create_index(op.f('ix_security_incidents_status'), 'security_incidents', ['status'], unique=False)
    op.create_index(op.f('ix_security_incidents_title'), 'security_incidents', ['title'], unique=False)
    op.create_index(op.f('ix_security_incidents_user_id'), 'security_incidents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_incidents_user_id'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_title'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_status'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_id'), table_name='security_incidents')
    op.drop_table('security_incidents')
    # ### end Alembic commands ###
