"""create_risk_assessments_table

Revision ID: d39a57b16627
Revises: acdf67703dc3
Create Date: 2026-09-25 19:31:52.712670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39a57b16627'
down_revision: Union[str, Sequence[str], None] = 'acdf67703dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=False),
    sa.Column('ml_raw_score', sa.Float(), nullable=False),
    sa.Column('ml_norm_score', sa.Float(), nullable=False),
    sa.Column('final_risk', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'window_start', name='uq_risk_assessment_user_window')
    )
    op.create_index('ix_risk_assessment_user_window', 'risk_assessments', ['user_id', 'window_start'], unique=False)
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_index('ix_risk_assessment_user_window', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
